import React from "react";
import { useParams } from 'react-router-dom';
import './Dynamic.css'

// images
import burgerImg from "../../images/burger.jpg"
import butterChickenImg from "../../images/butterChicken.jpg"
import cakeImg from "../../images/cake.jpg"
import chickenBiryaniImg from "../../images/ChickenBiryani.jpg"
import chickenCurryImg from "../../images/chickenCurry.jpg"
import eggSandwitchImg from "../../images/eggSandwitch.jpg"
import IceCofeeImg from "../../images/iceCofee.jpg"
import KabsaImg from  "../../images/Kabsa.jpg"
import khichdiImg from "../../images/khichdi.jpg"
import lasaniaImg from "../../images/lasania.jpg"

const DynnmicRecipe =(props)=>{

    const foods =[
        {name:"Burger", img:burgerImg , data: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quibusdam adipisci saepe odio quidem reprehenderit quam in numquam, earum optio molestias sequi laborum veritatis sint corrupti error aspernatur nihil distinctio ex eos magni aliquid cupiditate. Mollitia dolores ducimus perspiciatis ipsa aperiam corrupti rem iste. Vitae totam quos vel fugit dolor? Omnis nobis numquam quisquam atque libero magnam! Harum consequuntur ullam accusantium magnam numquam aperiam rem, eligendi voluptate perspiciatis ducimus error sequi officiis possimus iste minima. Eius necessitatibus similique qui doloribus, quia obcaecati quaerat ducimus maiores at impedit? Facere quia minima provident vitae qui totam necessitatibus officia? Exercitationem laudantium ab consequatur blanditiis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga magnam magni in enim molestias fugiat nesciunt ad sequi ullam vel. At, non nostrum? In distinctio labore numquam veniam excepturi consequuntur itaque earum nesciunt id laboriosam nobis rerum iste, ex veritatis animi magnam rem ipsa facere voluptas repellat fuga aliquid! Sequi, facere tempora. Nulla laborum magnam in? Nulla earum doloribus ut quis, soluta magni et obcaecati accusantium voluptatum cupiditate molestiae aperiam quia, architecto optio atque nemo totam est quisquam deserunt fuga eveniet quidem ducimus. Possimus unde cupiditate, laudantium distinctio vero repellendus, ipsam molestias quo illum quos ullam nulla eius odio dolores?"},
        {name:"Butter Chicken", img: butterChickenImg, data: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quibusdam adipisci saepe odio quidem reprehenderit quam in numquam, earum optio molestias sequi laborum veritatis sint corrupti error aspernatur nihil distinctio ex eos magni aliquid cupiditate. Mollitia dolores ducimus perspiciatis ipsa aperiam corrupti rem iste. Vitae totam quos vel fugit dolor? Omnis nobis numquam quisquam atque libero magnam! Harum consequuntur ullam accusantium magnam numquam aperiam rem, eligendi voluptate perspiciatis ducimus error sequi officiis possimus iste minima. Eius necessitatibus similique qui doloribus, quia obcaecati quaerat ducimus maiores at impedit? Facere quia minima provident vitae qui totam necessitatibus officia? Exercitationem laudantium ab consequatur blanditiis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga magnam magni in enim molestias fugiat nesciunt ad sequi ullam vel. At, non nostrum? In distinctio labore numquam veniam excepturi consequuntur itaque earum nesciunt id laboriosam nobis rerum iste, ex veritatis animi magnam rem ipsa facere voluptas repellat fuga aliquid! Sequi, facere tempora. Nulla laborum magnam in? Nulla earum doloribus ut quis, soluta magni et obcaecati accusantium voluptatum cupiditate molestiae aperiam quia, architecto optio atque nemo totam est quisquam deserunt fuga eveniet quidem ducimus. Possimus unde cupiditate, laudantium distinctio vero repellendus, ipsam molestias quo illum quos ullam nulla eius odio dolores?"},
        {name:"Cake", img: cakeImg, data: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quibusdam adipisci saepe odio quidem reprehenderit quam in numquam, earum optio molestias sequi laborum veritatis sint corrupti error aspernatur nihil distinctio ex eos magni aliquid cupiditate. Mollitia dolores ducimus perspiciatis ipsa aperiam corrupti rem iste. Vitae totam quos vel fugit dolor? Omnis nobis numquam quisquam atque libero magnam! Harum consequuntur ullam accusantium magnam numquam aperiam rem, eligendi voluptate perspiciatis ducimus error sequi officiis possimus iste minima. Eius necessitatibus similique qui doloribus, quia obcaecati quaerat ducimus maiores at impedit? Facere quia minima provident vitae qui totam necessitatibus officia? Exercitationem laudantium ab consequatur blanditiis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga magnam magni in enim molestias fugiat nesciunt ad sequi ullam vel. At, non nostrum? In distinctio labore numquam veniam excepturi consequuntur itaque earum nesciunt id laboriosam nobis rerum iste, ex veritatis animi magnam rem ipsa facere voluptas repellat fuga aliquid! Sequi, facere tempora. Nulla laborum magnam in? Nulla earum doloribus ut quis, soluta magni et obcaecati accusantium voluptatum cupiditate molestiae aperiam quia, architecto optio atque nemo totam est quisquam deserunt fuga eveniet quidem ducimus. Possimus unde cupiditate, laudantium distinctio vero repellendus, ipsam molestias quo illum quos ullam nulla eius odio dolores?"},
        {name:"Chicken Biryani", img: chickenBiryaniImg, data: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quibusdam adipisci saepe odio quidem reprehenderit quam in numquam, earum optio molestias sequi laborum veritatis sint corrupti error aspernatur nihil distinctio ex eos magni aliquid cupiditate. Mollitia dolores ducimus perspiciatis ipsa aperiam corrupti rem iste. Vitae totam quos vel fugit dolor? Omnis nobis numquam quisquam atque libero magnam! Harum consequuntur ullam accusantium magnam numquam aperiam rem, eligendi voluptate perspiciatis ducimus error sequi officiis possimus iste minima. Eius necessitatibus similique qui doloribus, quia obcaecati quaerat ducimus maiores at impedit? Facere quia minima provident vitae qui totam necessitatibus officia? Exercitationem laudantium ab consequatur blanditiis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga magnam magni in enim molestias fugiat nesciunt ad sequi ullam vel. At, non nostrum? In distinctio labore numquam veniam excepturi consequuntur itaque earum nesciunt id laboriosam nobis rerum iste, ex veritatis animi magnam rem ipsa facere voluptas repellat fuga aliquid! Sequi, facere tempora. Nulla laborum magnam in? Nulla earum doloribus ut quis, soluta magni et obcaecati accusantium voluptatum cupiditate molestiae aperiam quia, architecto optio atque nemo totam est quisquam deserunt fuga eveniet quidem ducimus. Possimus unde cupiditate, laudantium distinctio vero repellendus, ipsam molestias quo illum quos ullam nulla eius odio dolores?"},
        {name:"chicken Curry", img: chickenCurryImg, data: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quibusdam adipisci saepe odio quidem reprehenderit quam in numquam, earum optio molestias sequi laborum veritatis sint corrupti error aspernatur nihil distinctio ex eos magni aliquid cupiditate. Mollitia dolores ducimus perspiciatis ipsa aperiam corrupti rem iste. Vitae totam quos vel fugit dolor? Omnis nobis numquam quisquam atque libero magnam! Harum consequuntur ullam accusantium magnam numquam aperiam rem, eligendi voluptate perspiciatis ducimus error sequi officiis possimus iste minima. Eius necessitatibus similique qui doloribus, quia obcaecati quaerat ducimus maiores at impedit? Facere quia minima provident vitae qui totam necessitatibus officia? Exercitationem laudantium ab consequatur blanditiis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga magnam magni in enim molestias fugiat nesciunt ad sequi ullam vel. At, non nostrum? In distinctio labore numquam veniam excepturi consequuntur itaque earum nesciunt id laboriosam nobis rerum iste, ex veritatis animi magnam rem ipsa facere voluptas repellat fuga aliquid! Sequi, facere tempora. Nulla laborum magnam in? Nulla earum doloribus ut quis, soluta magni et obcaecati accusantium voluptatum cupiditate molestiae aperiam quia, architecto optio atque nemo totam est quisquam deserunt fuga eveniet quidem ducimus. Possimus unde cupiditate, laudantium distinctio vero repellendus, ipsam molestias quo illum quos ullam nulla eius odio dolores?"},
        {name:"Egg Sandwitch", img: eggSandwitchImg, data: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quibusdam adipisci saepe odio quidem reprehenderit quam in numquam, earum optio molestias sequi laborum veritatis sint corrupti error aspernatur nihil distinctio ex eos magni aliquid cupiditate. Mollitia dolores ducimus perspiciatis ipsa aperiam corrupti rem iste. Vitae totam quos vel fugit dolor? Omnis nobis numquam quisquam atque libero magnam! Harum consequuntur ullam accusantium magnam numquam aperiam rem, eligendi voluptate perspiciatis ducimus error sequi officiis possimus iste minima. Eius necessitatibus similique qui doloribus, quia obcaecati quaerat ducimus maiores at impedit? Facere quia minima provident vitae qui totam necessitatibus officia? Exercitationem laudantium ab consequatur blanditiis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga magnam magni in enim molestias fugiat nesciunt ad sequi ullam vel. At, non nostrum? In distinctio labore numquam veniam excepturi consequuntur itaque earum nesciunt id laboriosam nobis rerum iste, ex veritatis animi magnam rem ipsa facere voluptas repellat fuga aliquid! Sequi, facere tempora. Nulla laborum magnam in? Nulla earum doloribus ut quis, soluta magni et obcaecati accusantium voluptatum cupiditate molestiae aperiam quia, architecto optio atque nemo totam est quisquam deserunt fuga eveniet quidem ducimus. Possimus unde cupiditate, laudantium distinctio vero repellendus, ipsam molestias quo illum quos ullam nulla eius odio dolores?"},
        {name:"Ice Cofee", img: IceCofeeImg, data: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quibusdam adipisci saepe odio quidem reprehenderit quam in numquam, earum optio molestias sequi laborum veritatis sint corrupti error aspernatur nihil distinctio ex eos magni aliquid cupiditate. Mollitia dolores ducimus perspiciatis ipsa aperiam corrupti rem iste. Vitae totam quos vel fugit dolor? Omnis nobis numquam quisquam atque libero magnam! Harum consequuntur ullam accusantium magnam numquam aperiam rem, eligendi voluptate perspiciatis ducimus error sequi officiis possimus iste minima. Eius necessitatibus similique qui doloribus, quia obcaecati quaerat ducimus maiores at impedit? Facere quia minima provident vitae qui totam necessitatibus officia? Exercitationem laudantium ab consequatur blanditiis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga magnam magni in enim molestias fugiat nesciunt ad sequi ullam vel. At, non nostrum? In distinctio labore numquam veniam excepturi consequuntur itaque earum nesciunt id laboriosam nobis rerum iste, ex veritatis animi magnam rem ipsa facere voluptas repellat fuga aliquid! Sequi, facere tempora. Nulla laborum magnam in? Nulla earum doloribus ut quis, soluta magni et obcaecati accusantium voluptatum cupiditate molestiae aperiam quia, architecto optio atque nemo totam est quisquam deserunt fuga eveniet quidem ducimus. Possimus unde cupiditate, laudantium distinctio vero repellendus, ipsam molestias quo illum quos ullam nulla eius odio dolores?"},
        {name:"Kabsa", img: KabsaImg, data: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quibusdam adipisci saepe odio quidem reprehenderit quam in numquam, earum optio molestias sequi laborum veritatis sint corrupti error aspernatur nihil distinctio ex eos magni aliquid cupiditate. Mollitia dolores ducimus perspiciatis ipsa aperiam corrupti rem iste. Vitae totam quos vel fugit dolor? Omnis nobis numquam quisquam atque libero magnam! Harum consequuntur ullam accusantium magnam numquam aperiam rem, eligendi voluptate perspiciatis ducimus error sequi officiis possimus iste minima. Eius necessitatibus similique qui doloribus, quia obcaecati quaerat ducimus maiores at impedit? Facere quia minima provident vitae qui totam necessitatibus officia? Exercitationem laudantium ab consequatur blanditiis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga magnam magni in enim molestias fugiat nesciunt ad sequi ullam vel. At, non nostrum? In distinctio labore numquam veniam excepturi consequuntur itaque earum nesciunt id laboriosam nobis rerum iste, ex veritatis animi magnam rem ipsa facere voluptas repellat fuga aliquid! Sequi, facere tempora. Nulla laborum magnam in? Nulla earum doloribus ut quis, soluta magni et obcaecati accusantium voluptatum cupiditate molestiae aperiam quia, architecto optio atque nemo totam est quisquam deserunt fuga eveniet quidem ducimus. Possimus unde cupiditate, laudantium distinctio vero repellendus, ipsam molestias quo illum quos ullam nulla eius odio dolores?"},
        {name:"khichdi", img: khichdiImg, data: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quibusdam adipisci saepe odio quidem reprehenderit quam in numquam, earum optio molestias sequi laborum veritatis sint corrupti error aspernatur nihil distinctio ex eos magni aliquid cupiditate. Mollitia dolores ducimus perspiciatis ipsa aperiam corrupti rem iste. Vitae totam quos vel fugit dolor? Omnis nobis numquam quisquam atque libero magnam! Harum consequuntur ullam accusantium magnam numquam aperiam rem, eligendi voluptate perspiciatis ducimus error sequi officiis possimus iste minima. Eius necessitatibus similique qui doloribus, quia obcaecati quaerat ducimus maiores at impedit? Facere quia minima provident vitae qui totam necessitatibus officia? Exercitationem laudantium ab consequatur blanditiis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga magnam magni in enim molestias fugiat nesciunt ad sequi ullam vel. At, non nostrum? In distinctio labore numquam veniam excepturi consequuntur itaque earum nesciunt id laboriosam nobis rerum iste, ex veritatis animi magnam rem ipsa facere voluptas repellat fuga aliquid! Sequi, facere tempora. Nulla laborum magnam in? Nulla earum doloribus ut quis, soluta magni et obcaecati accusantium voluptatum cupiditate molestiae aperiam quia, architecto optio atque nemo totam est quisquam deserunt fuga eveniet quidem ducimus. Possimus unde cupiditate, laudantium distinctio vero repellendus, ipsam molestias quo illum quos ullam nulla eius odio dolores?"},
        {name:"lasania", img: lasaniaImg, data: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quibusdam adipisci saepe odio quidem reprehenderit quam in numquam, earum optio molestias sequi laborum veritatis sint corrupti error aspernatur nihil distinctio ex eos magni aliquid cupiditate. Mollitia dolores ducimus perspiciatis ipsa aperiam corrupti rem iste. Vitae totam quos vel fugit dolor? Omnis nobis numquam quisquam atque libero magnam! Harum consequuntur ullam accusantium magnam numquam aperiam rem, eligendi voluptate perspiciatis ducimus error sequi officiis possimus iste minima. Eius necessitatibus similique qui doloribus, quia obcaecati quaerat ducimus maiores at impedit? Facere quia minima provident vitae qui totam necessitatibus officia? Exercitationem laudantium ab consequatur blanditiis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga magnam magni in enim molestias fugiat nesciunt ad sequi ullam vel. At, non nostrum? In distinctio labore numquam veniam excepturi consequuntur itaque earum nesciunt id laboriosam nobis rerum iste, ex veritatis animi magnam rem ipsa facere voluptas repellat fuga aliquid! Sequi, facere tempora. Nulla laborum magnam in? Nulla earum doloribus ut quis, soluta magni et obcaecati accusantium voluptatum cupiditate molestiae aperiam quia, architecto optio atque nemo totam est quisquam deserunt fuga eveniet quidem ducimus. Possimus unde cupiditate, laudantium distinctio vero repellendus, ipsam molestias quo illum quos ullam nulla eius odio dolores?"},
      ]

    const {recipeName} = useParams();

    const nowFood = foods.filter((ele)=>{
        return ele.name === recipeName;
    })

    console.log(nowFood);

    


    return(
        <div>
            {nowFood.map((food)=>{
        return(
            <div className="dynamic">
                <img className="dynamicImg" src={food.img} alt={food.name}/>
                <h1>{food.name}</h1>
                <p className="recipe">{food.data}</p>
                <p className="apology">sorry these are not real recipes I was focused to make a web app in react so 
                I didn't collect any real recipes just used dummy texts. </p>
            </div>
        )
    })}
        </div>
    )
}

export default DynnmicRecipe;